### ISSUE TITLE
关于Github Releases

### ISSUE THREAD

**Issue by BnqDzj** [54ayao/JSDMirror#22]
目前Jsdelivr并没有支持Github Releases，有[提案](https://github.com/jsdelivr/jsdelivr/issues/18203)，但优先级较低，且过去了3年（从 2020年4月7日-至今）也并未实现，可以在 /gh-proxy 回源 ghproxy.com（也可以[自行搭建](https://github.com/hunshcn/gh-proxy)），或者重新定义一个子域名用于回源ghproxy，来达到支持Github Releases的目的

**Comment by 54ayao** [comment]
我们上游是Jsdelivr ，按照来说应该只支持其jsdelivr的生态规则，但是你这个你这个提议不错可以考虑考虑，
但是加速这个流量可能对于我们来说硬伤，可能不会集成在这个系统，等q4中旬差不多就可以了，你可以尝试访问这个URL 会301到你说的这个加速项目

**Comment by 54ayao** [comment]
否，
proxy.gitdw.com
proxy.gitkf.com
其一

**Comment by 54ayao** [comment]
详情查看独享域名政策
