### ISSUE TITLE
国外ipv6无法访问

### ISSUE THREAD

**Issue by xiaozhou26** [54ayao/JSDMirror#26]
国外会定向为vercel代理 的jsdelivr，vercel无ipv6

**Comment by xiaozhou26** [comment]
建议国外直接使用官方的链接，速度很快的

**Comment by 54ayao** [comment]
纯v6嘛 晚点看看这几天在处理反诈的事情

**Comment by 54ayao** [comment]
![微信截图_20240423144742](https://github.com/54ayao/JSDMirror/assets/86733666/4270a906-7191-40be-bfe8-a9832db8e2ad)
已支持 其次 官方链接不会考虑 ，之前是海外301官方，接到过国内的话使用海外DNS 和返回海外DNS导致无法访问问题 让CDN通过ip判断的话IPv6的准确性就不行了。可能错误判断成海外
