### ISSUE TITLE
今天访问github仓库里的图片，发现访问不了了，这是为何呢？

### ISSUE THREAD

**Issue by jackchoumine** [54ayao/JSDMirror#27]
![image](https://github.com/54ayao/JSDMirror/assets/21340150/535f82f6-c080-49cb-ba45-ed8b7f34095d)

https://jsd.cdn.zzko.cn/gh/jackchoumine/jack-picture@master/gitlab/%E6%89%8B%E5%8A%A8%E5%8F%91%E5%B8%83%E4%BA%86%E4%B8%80%E4%B8%AA%E7%89%88%E6%9C%AC.png

**Comment by 54ayao** [comment]
查不到日志了但是看了下COS里面的文件基本上没看到什么问题，已经移除了 并且提交到了CDN 请稍等5分钟后再次尝试

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/JSDMirror/assets/86733666/86200d00-285b-4932-aeff-81c3592d339f)

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/JSDMirror/assets/86733666/5fb8946f-19d3-482c-af13-6b9402fce655)
生效了辛苦再看一下
![image](https://github.com/54ayao/JSDMirror/assets/86733666/dbaddb3e-b2f6-4670-897d-567ba8a55ff8)
