### ISSUE TITLE
请问默认服务器缓存时长是多久？

### ISSUE THREAD

**Issue by i18n-now** [54ayao/JSDMirror#28]
如题

我有一个curl的bash脚本检查版本号，我想知道如果不手动刷新，多久能看到更变

**Comment by 54ayao** [comment]
/gh/ 是7天 
/npm/ 14天
/wp/ 一个月
图片类一年

在上游清理完成后可以使用api清理，

**Comment by 54ayao** [comment]
.sh 如果需要的话，后续做遵守源站处理。

**Comment by i18n-now** [comment]
明白，多谢

**Comment by lzfxxx** [comment]
> /gh/ 是7天 /npm/ 14天 /wp/ 一个月 图片类一年
> 
> 在上游清理完成后可以使用api清理，

请问 API 怎么调用，没有找到文档
