### ISSUE TITLE
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'

### ISSUE THREAD

**Issue by i18n-now** [54ayao/JSDMirror#29]
海外是正常的，本地和阿里云访问报错
本地

❯ curl  https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
❯ ping cdn.jsdmirror.com
PING cdn.jsdmirror.com.cdn.domaincdn.cn (124.202.188.212): 56 data bytes
64 bytes from 124.202.188.212: icmp_seq=0 ttl=55 time=17.154 ms
64 bytes from 124.202.188.212: icmp_seq=1 ttl=55 time=13.014 ms

❯ curl -i  https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

---

阿里云服务器

❯ ping cdn.jsdmirror.com
PING cdn.jsdmirror.com(240e:ab:b210:500::58 (240e:ab:b210:500::58)) 56 data bytes
64 bytes from 240e:ab:b210:500::58 (240e:ab:b210:500::58): icmp_seq=1 ttl=54 time=37.7 ms
64 bytes from 240e:ab:b210:500::58 (240e:ab:b210:500::58): icmp_seq=2 ttl=54 time=37.7 ms
^C
--- cdn.jsdmirror.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 37.662/37.667/37.673/0.005 ms
❯ curl -i  https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by 54ayao** [comment]
更新了再看看？

**Comment by i18n-now** [comment]
我看证书是  *  subject: CN=*.cdn.myqcloud.com


❯ curl -vI  https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18
*   Trying 124.202.188.79:443...
* Connected to cdn.jsdmirror.com (124.202.188.79) port 443
* ALPN: curl offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=*.cdn.myqcloud.com
*  start date: Aug  9 00:00:00 2023 GMT
*  expire date: Sep  7 23:59:59 2024 GMT
*  subjectAltName does not match cdn.jsdmirror.com
* SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'
* Closing connection
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.jsdmirror.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by i18n-now** [comment]
现在可以了

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/JSDMirror/assets/86733666/7901ca77-a977-49ae-806c-90cb4586cc81)
阈值低了
