### ISSUE TITLE
https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18 清理缓存一直无效

### ISSUE THREAD

**Issue by i18n-now** [54ayao/JSDMirror#30]
截图如下
![image](https://github.com/54ayao/JSDMirror/assets/145643935/4329cbb2-9d7e-4804-aae3-0baa7c7e540c)
<img width="1280" alt="image" src="https://github.com/54ayao/JSDMirror/assets/145643935/ec0ae00c-c3fe-416b-950f-9d0a78f75c0e">
我早上清理过一次，刚刚又清理过一次，但是一直没更新
curl -i  https://cdn.jsdmirror.com/gh/i18n-site/dist@v/i18

**Comment by i18n-now** [comment]
另外，这里微信群满了, 怎么加微信群

<img width="1380" alt="image" src="https://github.com/54ayao/JSDMirror/assets/145643935/74f7935e-6268-43f2-b6ae-52f6648a8b31">

**Comment by 54ayao** [comment]
目录是要已/结尾

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/JSDMirror/assets/86733666/d5efb181-4d41-4c1f-a696-ec49aad8841a)
不行试试 com换cn看看？

**Comment by 54ayao** [comment]
![image](https://github.com/54ayao/JSDMirror/assets/86733666/18ff5162-e63f-43c3-af8e-911754992d06)

**Comment by 54ayao** [comment]
先用cn 我看看什么原因

**Comment by i18n-now** [comment]
嗯，我不着急，就是感觉是一个bug
cn是一个会长期维护的域名吗？

**Comment by 54ayao** [comment]
群的话是微信限制了 没交保护费

**Comment by 54ayao** [comment]
cn和com是同时发版的 底层都是一样的 com优先级高 cn目前是发布演练用的

**Comment by 54ayao** [comment]
这个星期内解决吧

**Comment by 54ayao** [comment]
处理了一些违规的URL，看了一下问题，现在应该正常了吧

**Comment by 54ayao** [comment]
你可以再试试，并且给你补发了一点积分，可在积分详情查看，如果没有到账的话签到一次试试，单节点是最近违规违规用户的网站请求比较多 解析的是cdn演练IP来排查违规用户的，和生产环境是隔离的，所以说导致不生效

**Comment by i18n-now** [comment]
多谢。
