### ISSUE TITLE
分享一个便宜的cdn，没有https费 ,1G5分钱。

### ISSUE THREAD

**Issue by i18n-now** [54ayao/JSDMirror#31]
分享一个便宜的cdn，没有https费 ,1G5分钱https://www.dfyun.com.cn/

**Comment by 54ayao** [comment]
和合作商合同暂时未到期 暂不考虑 他们单价也是几分钱 没有https计费 
https://www.baishan.com/pages/about/about/

**Comment by 54ayao** [comment]
我们有考虑过自建
![1718727129083.jpg](https://github.com/54ayao/JSDMirror/assets/86733666/24941827-8222-466c-bf47-45cc78142521)


![IMG_20240619_001258.jpg](https://github.com/54ayao/JSDMirror/assets/86733666/f252b126-da86-4955-998f-729c4286bec2)

和小厂也有合作

**Comment by i18n-now** [comment]
感觉，可以搞一个开源项目，大家可以把自己的限制服务器贡献出来，大家还可以赚积分。
自己搞个dns服务器应该就可以实现了。
用rust写应该挺简单。

**Comment by 54ayao** [comment]
他们家是要签合同的，不支持个人

**Comment by 54ayao** [comment]
应该可以，但是该域名底层配置复杂 普通cdn程序基本上无法满足。 edgego 倒是可以授权费用比较高，底层系统有黑名单，白名单，审核系统，加速源，备用加速，每一个sni都不一样

**Comment by i18n-now** [comment]
我的想法是基于 Pingora 和 hickory-dns ，自己写一个，
前端用 serviceWorker.js  做一层拦截，可以比较容易的做到高可用

https://github.com/hickory-dns/hickory-dns
CloudFlare宣布开源Pingora框架 基于Rust编写 用来替代Nginx
https://www.landiannews.com/archives/102628.html

感觉是个挺有趣的方向，不过最近太忙，没空折腾，哈哈。
