### ISSUE TITLE
清理缓存还是有问题

### ISSUE THREAD

**Issue by i18n-now** [54ayao/JSDMirror#32]
![image](https://github.com/54ayao/JSDMirror/assets/145643935/884de74b-5220-47ee-bae9-547d19c3d044)

jsdelivr 是 12 

jsdmirror 是 6 和 7

```
❯ curl  https://cdn.jsdelivr.net/npm/i18md/.v
0.1.12>0.1.8
❯ ping cdn.jsdmirror.com
PING cdn.jsdmirror.com.cdn.domaincdn.cn (124.205.198.164): 56 data bytes
❯ curl  https://cdn.jsdmirror.com/npm/i18md/.v
0.1.7>0.1.8%
❯ curl  https://cdn.jsdmirror.com/npm/i18md/.v
0.1.6>0.1.4%
❯
❯ ping cdn.jsdmirror.com
PING cdn.jsdmirror.com.cdn.domaincdn.cn (124.203.225.206): 56 data bytes
64 bytes from 124.203.225.206: icmp_seq=0 ttl=52 time=47.765 ms


```

<img width="659" alt="image" src="https://github.com/54ayao/JSDMirror/assets/145643935/0ac6bd74-9af4-40d7-bbee-c225c4b2536a">

**Comment by i18n-now** [comment]
哦 ，现在好了，延时有点久

**Comment by 54ayao** [comment]
cf-ray 这里说明了是cloudflaer,海外cdn不支持清理，还没有开发出来 但是看ping的IP是124.205.198.164 北京鹏博士，看起来不是CDN的IP

**Comment by 54ayao** [comment]
国内机器。需要检查dns是否为非8.8.8.8 1.1.1.1 4.4.2.2 等海外的的dns
由于他们dns时并没有在国内部署dns节点就会被识别成亚太用户，走亚太线路。
可以试试119.29.29.29 jsdmirror和119.29.29.29有联动 有个递归加速解析
