### ISSUE TITLE
combine 开头路径报404

### ISSUE THREAD

**Issue by stevieyu** [54ayao/JSDMirror#33]
https://cdn.jsdmirror.com/combine/npm/video.js@8/dist/video.min.js,npm/swarmcloud-hls@latest/dist/p2p-engine.min.js
![image](https://github.com/54ayao/JSDMirror/assets/8325201/0c458a64-294b-49c0-b373-31c9ed2f4fe8)

远程地址: 93.177.76.245:443

**Comment by 54ayao** [comment]
海外cdn问题配置问题，在修了，

**Comment by 54ayao** [comment]
辛苦再看一下谢谢
