### ISSUE TITLE
境内站是不是崩了啊

### ISSUE THREAD

**Issue by Regionnor** [54ayao/JSDMirror#34]
如图，这是你们在blog.jsdmirror.com中所展示的cdn加速网站
![image](https://github.com/54ayao/JSDMirror/assets/132432401/6ab8300f-f531-45f0-905a-6dea843ba072)
对于我在GitHub上的同一个资源，cdn.jsdelivr.us是可以正常访问的，然而在cdn.jsdmirror.com中会自动跳转到www.jsdelivr.ren而且提示404 Not Found你们可以看一下这两个网站
同时，这个资源在cdn.jsdelivr.net同样也可以打开
【资源的地址】https://github.com/Regionnor/CDN/blob/main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
【国际站】https://cdn.jsdelivr.us/gh/Regionnor/CDN@main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
![image](https://github.com/54ayao/JSDMirror/assets/132432401/5fc486c6-bfae-498b-96e3-76baa2816e0e)
【境内站】https://www.jsdelivr.ren/gh/Regionnor/CDN%40main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
![image](https://github.com/54ayao/JSDMirror/assets/132432401/d6cb453b-f50a-4c5f-a50f-bd78b3182064)

**Comment by 54ayao** [comment]
审核系统逻辑代码被注释掉了，再看看？

**Comment by 54ayao** [comment]
具体逻辑就是当用户请求图片类型加速的时候会腾讯云触发审核，审核的话是在广州审核，然后由于审核要保存一份文件，就跳转到这个域名，然后下载完成之后审核提供之后再提交到cdn，如果没问题就加速，有问题就显示451，前两天换cdn的时候，在服务器中把审核系统先下了，提示Failed to fetch version info for Regionnor先看看别的文件，我现在上cf清一下缓存

**Comment by 54ayao** [comment]
用%40好像有点问题，下午在修，之前都是可以的，要找一下备份文件

**Comment by 54ayao** [comment]
审核不在用CF返回结果了 晚点迁移走

**Comment by 54ayao** [comment]
已迁移走 有时间辛苦再看看啦

**Comment by Regionnor** [comment]
现在应该是没什么问题了
【%40】https://www.jsdelivr.ren/gh/Regionnor/CDN%40main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
![image](https://github.com/54ayao/JSDMirror/assets/132432401/95ae9980-abbb-4803-aabb-f1ecc9ce1591)
【@】https://www.jsdelivr.ren/gh/Regionnor/CDN@main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
![image](https://github.com/54ayao/JSDMirror/assets/132432401/b241011b-72c6-4659-adbe-5eb5ded077c4)
但是综合访问速度还是有点小慢，5s-10s上下波动

**Comment by 54ayao** [comment]
审核完成之后他会回到。 cdn.jsdmirror.com的 好像是浏览器缓存导致的

**Comment by 54ayao** [comment]
https://cdn.jsdmirror.com/gh/Regionnor/CDN@main/img/OHR.LupinIceland_ZH-CN5329147708_UHD.jpg
我们目前是按照文件名为纬度。进行审核的审核过了他就回去了，

**Comment by 54ayao** [comment]
https://blog.jsdmirror.com/19.html
可参考本篇文章
在最新版本中。中国香港被移出来了，直接走到中国广州 审核两次的话，成本太高了。

**Comment by 54ayao** [comment]
这样吧，@转%40 我们在定位一下是服务器还是cos问题

**Comment by Regionnor** [comment]
> 审核完成之后他会回到。 cdn.jsdmirror.com的 好像是浏览器缓存导致的

我之前测速也是和现在一样，直连到网站并且禁用缓存和保留日志
![image](https://github.com/54ayao/JSDMirror/assets/132432401/ace04b8c-6002-4ee4-b105-d59eb4321489)
![image](https://github.com/54ayao/JSDMirror/assets/132432401/54c38de2-14d9-40cf-82dd-ec2dd0ab1c10)
现在来说不管是<code>@</code>还是<code>%40</code>访问速度是挺快的，可以在500ms-1s内上下波动

**Comment by 54ayao** [comment]
那，应该是cdn缓存了，只要保持写 cdn.jsdmirror.com 缓存一般很快就过期了。就能用新的了。

**Comment by 54ayao** [comment]
提供一下节点信息吧。

**Comment by 54ayao** [comment]
等一段时间应该会更快，因为目前没啥Money运营了，我们预估（控制台层面可见的）现在还欠cdn的钱，截止目前已经不少了，他到现在不给我出账单，我们也不敢接着用，我现在就是问我朋友到处借机器，用他们的闲置算力，想了一下如果学某些切到海外。可能有一定影响，等到这个问题解决了，我们换回去国内cdn

**Comment by Regionnor** [comment]
我这边在邮件看到你问过我有关节点信息的，应该指的是远程地址吧？
【境内站】远程地址:93.177.76.229:443
【国际站】远程地址:93.177.76.245:443

**Comment by 54ayao** [comment]
现在应该没问题了 ，dns知道你在大陆，速度基本上强一点点了

**Comment by Regionnor** [comment]
镜内站https://cdn.jsdelivr.us/又崩了？国际站还是正常的
![image](https://github.com/54ayao/JSDMirror/assets/132432401/bb99b1a2-e88f-4b01-9c6a-73c37bfe067c)

**Comment by 54ayao** [comment]
审核图片是HK HK BPG 这几天天天被打 扫段 然后G了

**Comment by 54ayao** [comment]
![Screenshot_2024-07-01-18-19-54-271_com.android.mms.jpg](https://github.com/54ayao/JSDMirror/assets/86733666/bed46d0b-5076-4c89-a38a-b3f0f93dc2f9)

**Comment by 54ayao** [comment]
![Screenshot_2024-07-01-18-19-54-271_com.android.mms.jpg](https://github.com/54ayao/JSDMirror/assets/86733666/bed46d0b-5076-4c89-a38a-b3f0f93dc2f9)

**Comment by i18n-now** [comment]
> 等一段时间应该会更快，因为目前没啥Money运营了，我们预估（控制台层面可见的）是已经欠cdn供应商的钱了，截止目前已经不少了，他到现在不给我出账单，我们也不敢接着用，我现在就是问我朋友到处借机器，用他们的闲置算力，想了一下如果学某些切到海外。可能有一定影响，等到这个问题解决了，我们换回去国内cdn

可以搞一个付费白名单的功能吗？

**Comment by 54ayao** [comment]
这一块是有的
https://www.jsdmirror.com/xzzo/
参考这里,目前没公开的原因就是因为cdn价格还没压下来。我大概要压 35左右

**Comment by 54ayao** [comment]
cdn.jsdmirror.com 有一个白名单系统理论上也可以支持，这个是免费的，但是图片还是要走一层转换。。。因为就算开白了，我们也不能保证储存的图片没办法向对方保证一定就是合法合规的。然后在里面储存一份的话，如果有违规的话，对方会及时通知我们。我们也好做做处理，而不是机器乱搞。

**Comment by i18n-now** [comment]
https://cdn.jsdmirror.com/npm/@8n/site@0.1.36/-.css
css也会被拦截

![CleanShot 2024-07-02 at 20 18 03@2x](https://github.com/54ayao/JSDMirror/assets/145643935/6cfee623-b222-4456-8ce1-e4cfc1fb0d0d)
https://cdn.jsdelivr.net/npm/@8n/site@0.1.36/-.css

**Comment by 54ayao** [comment]
有个ip移除了 晚点再看看

**Comment by huxxhua** [comment]
大佬，github page的图片，国内访问大部分都会404，但是偶尔又可以看到图
应该是个什么情况

![CleanShot 2024-07-05 at 11 10 24@2x](https://github.com/54ayao/JSDMirror/assets/20944512/9a33b915-bc74-4f5d-a0a7-80fc3beb83db)

**Comment by 54ayao** [comment]
方便发地址么 不方便加我 t.me/@YaoAYaoU

**Comment by 54ayao** [comment]
> 大佬，github page的图片，国内访问大部分都会404，但是偶尔又可以看到图
> 应该是个什么情况
> 
> 用的cdn地址是` jsd.cdn.zzko.cn`
> 
> ![CleanShot 2024-07-05 at 11 10 24@2x](https://github.com/54ayao/JSDMirror/assets/20944512/9a33b915-bc74-4f5d-a0a7-80fc3beb83db)
> 

方便发地址么 不方便加我 t.me/@YaoAYaoU方便发地址么 不方便加我 t.me/@YaoAYaoU

**Comment by Regionnor** [comment]
对于同一个仓库的资源，一个可以正常打开，一个显示HTTP ERROR 418，这是怎么回事啊
> ![屏幕截图 2024-07-07 123402](https://github.com/54ayao/JSDMirror/assets/132432401/26ad5408-3b67-4595-a401-29205f254afc)
> https://cdn.jsdmirror.com/gh/Regionnor/CDN@main/img/p1958733032.webp

> ![屏幕截图 2024-07-07 123414](https://github.com/54ayao/JSDMirror/assets/132432401/11738838-3d83-4a4a-a8cc-638357439c3c)
> https://cdn.jsdmirror.com/gh/Regionnor/CDN@main/img/p2896540062.webp

> ![image](https://github.com/54ayao/JSDMirror/assets/132432401/89980af1-edfc-41e7-8dce-87ca947c4f7e)
> https://cdn.393837.xyz/img/p2896540062.webp

**Comment by 54ayao** [comment]
> 对于同一个仓库的资源，一个可以正常打开，一个显示HTTP ERROR 418，这是怎么回事啊
> > ![屏幕截图 2024-07-07 123402](https://github.com/54ayao/JSDMirror/assets/132432401/26ad5408-3b67-4595-a401-29205f254afc)
> > https://cdn.jsdmirror.com/gh/Regionnor/CDN@main/img/p1958733032.webp
> 
> > ![屏幕截图 2024-07-07 123414](https://github.com/54ayao/JSDMirror/assets/132432401/11738838-3d83-4a4a-a8cc-638357439c3c)
> > https://cdn.jsdmirror.com/gh/Regionnor/CDN@main/img/p2896540062.webp
> 
> > ![image](https://github.com/54ayao/JSDMirror/assets/132432401/89980af1-edfc-41e7-8dce-87ca947c4f7e)
> > https://cdn.393837.xyz/img/p2896540062.webp
> > 这是那张无法正常打开的图片

平台。这几天20:00-23:00点都遭受到了攻击，针对cdn的纯属报复行为，影响用户较为广泛

目前是山西太原联通，（家庭宽带）我们这几天计划向嫌疑人所在地的110报警中心寻求帮助，包括腾讯这边也在积极收集证据，腾讯云这边最近也在协助我们这群被攻击的人，但是怎么说呢，由于他每天都定时攻击换ip，他还是hosts，人工干预难度很大。，官方建议是先停掉那一个骨干网访问，如果的话只能先是把山西联通先禁止访问，考虑到影响范围比较大，我们就暂没有设置，下午已经切换了一个策略。有时间再试试吧。

**Comment by Regionnor** [comment]
cdn被打有可能是同行所为，反正先希望能尽快把嫌疑人抓住吧
现在<code>https://cdn.jsdelivr.us</code>显示<code>无法提供安全连接</code>也是因为这件事吗
![image](https://github.com/54ayao/JSDMirror/assets/132432401/4cd11e5d-4d60-4ad0-9395-81d26a659081)

**Comment by 54ayao** [comment]
> cdn被打有可能是同行所为，反正先希望能尽快把嫌疑人抓住吧
> 现在<code>https://cdn.jsdelivr.us</code>显示<code>无法提供安全连接</code>也是因为这件事吗
> ![image](https://github.com/54ayao/JSDMirror/assets/132432401/4cd11e5d-4d60-4ad0-9395-81d26a659081)

1.这是针对Edgeone攻击行为，已经有大量用户遭殃了，每天都是我们相同的ip都被打。很离谱的就是怎么会有大量山西太原家庭ip，初步怀疑是运营商问题吧。比如说赠送的路由器有漏洞啊。是怎么样的？我们近期看看联系山西那网安联动一下山西联通排查一下

2.否 我一会看看

**Comment by i18n-now** [comment]
归属地： 
中国 北京市 朝阳区
运营商：
中国电信
本机IP：
101.39.212.90

北京的ip无法访问 https://blog.jsdmirror.com/

![CleanShot 2024-07-16 at 18 02 23](https://github.com/user-attachments/assets/a7addcaf-4d0e-4546-9f0f-492c89f0543c)

**Comment by 54ayao** [comment]
访问受到限制？ QPS吧 晚点看看

**Comment by 54ayao** [comment]
10秒内请求文件超过35次，晚点我改一下设置吧
