### ISSUE TITLE
451 Unavailable For Legal Reasons

### ISSUE THREAD

**Issue by cn-vhql** [54ayao/JSDMirror#35]
请问所有的图片出现这个是什么原因，求解决
https://jsd.cdn.zzko.cn/gh/cn-vhql/picture/picture_bed/202406232114196.png
https://jsd.cdn.zzko.cn/gh/cn-vhql/picture/picture_bed/202406291249922.png
![image](https://github.com/54ayao/JSDMirror/assets/103089105/7890bcf0-4c28-4143-9ec0-3fede82be70f)

**Comment by dqwyy** [comment]
我也出现了相同的情况。
https://cdn.jsdmirror.com/gh/dqwyy/vrc-teo/image/avatar/niko.jpg
https://jsd.cdn.zzko.cn/gh/dqwyy/vrc-teo/image/avatar/vnts.jpg
https://cdn.jsdmirror.com/gh/dqwyy/vrc-teo/image/avatar/tom.jpg

**Comment by 54ayao** [comment]
已处理，有空再看看，欠费保护了

**Comment by 54ayao** [comment]
https://jsd.cdn.zzko.cn/gh/cn-vhql/picture/picture_bed/202406291249922.png
![image](https://github.com/54ayao/JSDMirror/assets/86733666/9e30a293-5ce4-4a0a-a9f6-334c55243187) 已解封

**Comment by 54ayao** [comment]
451 由于这两种情况，欠费封禁还有就是违规封禁
页面丰富一点的就是违规封禁，稍微没什么代码的，那就是欠费封禁，account 就是欠费了，不会太过于关注账号剩下多少()
