### ISSUE TITLE
文件加速时被重定向至 mirror.awhh.cn，请问这是正常现象吗？

### ISSUE THREAD

**Issue by yoghurtlee-thu** [54ayao/JSDMirror#36]
如题。在检查项目内 CDN 文件情况时发现链接被重定向到了题目中所述的链接。我人工比对了数十个 JavaScript 文件，暂时没有发现其他的异常。但由于在 jsdmirror 的官方网站上没有找到关于此情况的说明，所以想问一下这是正常现象吗？

此致。

**Comment by 54ayao** [comment]
可以看whois 都是我们的域名，嗯有点不符合预期，已经调整了。

**Comment by 54ayao** [comment]
域名

AWHH.CN

注册商

腾讯云计算（北京）有限责任公司

注册人

大连市泽瑶网络科技有限公司

邮箱

ayao@cola.email

注册日

2024-03-02 10:14:27 

UTC+8过期日

2025-03-02 10:14:27 

UTC+8状态

ok

DNS

sloan.ns.cloudflare.com

theo.ns.cloudflare.com

DNSSEC

未配置

**Comment by yoghurtlee-thu** [comment]
好的，主要是之前曾经遇到过公益 CDN 被恶意劫持的情况，因此有些担心。感谢您的解答，祝 JSDMirror 越来越好。
