### ISSUE TITLE
网页图片打不开

### ISSUE THREAD

**Issue by miaoyanginfo** [54ayao/JSDMirror#37]
请教一下，我在github搭了图床，在cloudflare使用了重定向规则，国内ip走jsdmirror，国外走jsdelivr。现在的问题是我页面调用的图片无法打开，但是把图片链接复制到浏览器之后可以正常跳转到jsdmirror。（更奇怪的是我用苹果的safari浏览器页面图片正常显示。edge和chrome均不正常）。
[网页链接](http://miaoyang.win/about/test)。图片链接：http://cdn.miaoyang.win/gh/miaoyanginfo/hexo-img/img/1280x720.png
想问一下我应该从哪里排查问题呢？

**Comment by miaoyanginfo** [comment]
另外我是按照这篇教程做的设置https://www.haoyep.com/posts/github-graph-beds-cdn/

**Comment by 54ayao** [comment]
看了一下 http 可以 https 不可以 查一下证书吧

**Comment by 54ayao** [comment]
页面规则设置指定域名不进行https

**Comment by miaoyanginfo** [comment]
> 页面规则设置指定域名不进行https

![image](https://github.com/user-attachments/assets/b5f332e5-23c0-4c66-95e6-d62342c165b3)
是这样设置吗？另外二级域名申请ssl证书好像要收费。没有外币卡。。
![image](https://github.com/user-attachments/assets/43ea8b11-02a2-4657-a8b3-51c8ef5ae3e7)

**Comment by 54ayao** [comment]
有没有远程控制软件类似于向日葵之类的 发送到ayao@cola.email 帮你看看?
证书是免费的 ns接入不收费
saas接入 不一定需要借记卡 我都是国内储蓄卡绑定PayPal验证都可以

**Comment by miaoyanginfo** [comment]
谢谢老哥。向日葵信息已发送到邮箱

**Comment by miaoyanginfo** [comment]
我已经订阅saas了，您不忙的时候帮忙瞅瞅，感谢

**Comment by 54ayao** [comment]
好的 现在方便吗？

**Comment by miaoyanginfo** [comment]
感谢感谢，订阅saas申请证书之后目前已经一切正常。感谢老哥
