### ISSUE TITLE
ERROR: ACCESS DENIED

### ISSUE THREAD

**Issue by liaohengfeng** [54ayao/JSDMirror#38]
`https://cdn.jsdmirror.cn/npm/@fortawesome/fontawesome-free@6.5.1/webfonts/fa-regular-400.woff2` 报 `ERROR: ACCESS DENIED` 返回 `403`。

`https://gcore.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.1/webfonts/fa-regular-400.woff2`  能正常访问。

**Comment by 54ayao** [comment]
核实了短时间内 waf请求了100次 可能ai分析导致相同URL被同一个ip访问被拉黑 waf层面有缓存，然后 /24被拉黑一大半 回源hash对不上了 就显示新的了被拉黑的页面 再看看呢

**Comment by 54ayao** [comment]
![image](https://github.com/user-attachments/assets/3fc5d6f7-735e-4b3f-ac3d-e742bd17aed8)
最近在收集一些不友好的IP策略上没有同步给cdn导致的 （当初考虑CDN会返回缓存没办法识别不友好的ip不返回内容）
